# Simple workflow for deploying static content to GitHub Pages
name: Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: true
      - name: Synch
        run: rsync -avzhHl /home/webuser/actions-runner-blog/_work/blog/blog/blog/blog/content /home/webuser/blog/blog
      - name: Test
        run: echo "Done!"

